# This is a namespace agnostic configuration file for the Franka FR3 robot.
# That is to say, it is not tied to any specific namespace and can be used in
# any namespace. 
# If you require namespace specific configurations, you can easily modify this
# file to include the namespace
# As an example, below you can find:
#
# /**:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 5
#       lock_sleep_interval: 5
#
# Imagine, you have a specific need to have the lock try count in namespace "NAMESPACE_X"
# to be different than the default value of 5, but leave all the other namespaces as default.
# Add the following lines to the configuration file 
# (or use a different config file, but then you have to mody the launch script to reference that file)
#
# /NAMESPACE_X:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 10
#       lock_sleep_interval: 35
# /**:
#   franka_robot_state_broadcaster:
#     ros__parameters:
#       lock_try_count: 5
#       lock_sleep_interval: 5


/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      thread_priority: 98

      handshake_controller:
        type: franka_handshake_controllers/HandShakeController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
        state_interfaces:
          robot_state


/**:
  franka_robot_state_broadcaster:
    ros__parameters:
      lock_try_count: 5 # Number of attempts to acquire the lock in a single on_update()
      lock_sleep_interval: 5 # microseconds sleep between attempts
      lock_log_error: true #  Log error if lock acquisition fails - false == do not log  
      lock_update_success: false # return update OK, although lock fails (no update occurs)
      
/**:
  handshake_controller:
    ros__parameters:
      arm_id: "fr3"    
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5

/**:
  joint_state_broadcaster:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7