controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    handshake_controller:
      type: "franka_handshake_controllers/HandShakeController"
      arm_id: "fr3"  # or whatever matches your URDF joint prefix

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

handshake_controller:
  ros__parameters:
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 56.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5
    dQ1: [0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0]
    dQ2: [0.0, 0.0, 0.0, -0.2, 0.0, 0.0, 0.0]
